version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: "npm install"
      - run:
          name: Run Tests
          command: "npm test"
      - run:
          name: Build Project
          command: "npm run build"
      - run:
          name: Package App
          command: |
            cp package.json dist
            cd dist
            tar -czf announcer_bot.tar.gz *
            mv announcer_bot.tar.gz ~/project
      - save_cache:
          name: Save Packer definition
          key: packer-{{epoch}}
          paths:
            - ~/project/docker/announcer_bot.json
      - save_cache:
          name: Save binaries for next job
          key: binaries-{{epoch}}
          paths:
            - ~/project/announcer_bot.tar.gz
      - store_test_results:
        path: test-results
  deploy:
    machine: true
    steps:
      - restore_cache:
          name: Restore Packer definition
          key: packer-
      - restore_cache:
          name: Restore binaries
          key: binaries-
      - run:
          name: Download Packer
          command: |
            wget https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
            unzip packer_1.4.2_linux_amd64.zip
      - run:
          name: Log into Docker Hub
          command: docker login -u $username -p $password
      - run:
          name: Build announcer_bot image
          command: |
            ./packer validate docker/announcer_bot.json
            ./packer build docker/announcer_bot.json
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
